# Render Blueprint for the Order Tools Flask Application
# https://render.com/docs/blueprints

services:
  - type: web
    name: order-tools
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app" # Ensure app:app matches your Flask app object name
    plan: starter # こちらはWebサービス自体のプランです。必要に応じて変更してください。
    envVars:
      - key: DATABASE_URL # PostgreSQL database URL will be injected by Render
        fromDatabase:
          name: order_tools_db
          property: connectionString
      - key: SECRET_KEY # A strong, random key for Flask session security
        generateValue: true # Render will generate a random value for you
      - key: PYTHON_VERSION
        value: 3.9.12 # Or your preferred Python version, e.g., 3.10.x, 3.11.x
    healthCheckPath: / # Or a specific endpoint if you have one, e.g., /api/health

databases:
  - name: order_tools_db
    plan: free # 'eco'から'free'に変更しました。無料プランですが30日の有効期限があります。